# Generated by Django 2.2.6 on 2020-01-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='upload',
            field=models.ImageField(null=True, upload_to='staff_uploads/'),
        ),
    ]
