# Generated by Django 2.2.6 on 2020-01-21 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Title'),
        ),
    ]
