# Generated by Django 2.2.6 on 2020-01-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmwnt_date',
            new_name='appointment_date',
        ),
    ]
