# Generated by Django 2.2.6 on 2020-01-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200120_1642'),
        ('appointments', '0002_auto_20200120_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Staff'),
        ),
    ]
